---

- name: Ensure systemd package is present
  ansible.builtin.package:
    name: systemd
    state: present

- name: Include systemd-unit
  ansible.builtin.include_tasks: systemd-unit.yml
  vars:
    dstunit: tinyproxy
    t: tinyproxy
    src: systemd-override.conf.j2
    dest: override.conf
