---

- name: Verify
  hosts: tinyproxy
  gather_facts: true
  vars:
    is_container: false
  pre_tasks:
    - name: RedHat | Ensure pgrep is present
      ansible.builtin.package:
        name: procps-ng
        state: present
      when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] | int >= 8
    - name: Debian | Ensure ps is present
      ansible.builtin.package:
        name:
          - procps
        state: present
      when: ansible_facts['os_family'] == "Debian"
    - name: Debug | ansible_facts['virtualization_type']
      ansible.builtin.debug:
        var: ansible_facts['virtualization_type']
        verbosity: 1
    - name: Set fact is_container
      ansible.builtin.set_fact:
        is_container: true
      when: >
        (ansible_facts.virtualization_type is defined and
          (ansible_facts.virtualization_type == "docker" or ansible_facts.virtualization_type == "containerd")
        )
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto
  tasks:
    - name: Validate that needed packages are present
      ansible.builtin.assert:
        that:
          - ansible_facts.packages['tinyproxy'] is defined

    - name: Ensure process is running
      ansible.builtin.command: pgrep -u tinyproxy tinyproxy
      register: ps
      changed_when: false
      failed_when: false
    - name: Validate ps output
      ansible.builtin.assert:
        that: ps.stdout | length > 0
      when:
        - not is_container|bool

    - name: Ensure ports are listening
      ansible.builtin.wait_for:
        host: "{{ item.h }}"
        port: "{{ item.p }}"
        timeout: 10
      with_items:
        - { h: localhost, p: 8888 }
      when:
        - not is_container|bool
